version: '3.8'
services:
  stat_buddy_service:
    build: .
    container_name: stat_buddy_service
    environment:
      - 'spring.profiles.active=dev'
      - 'DB_HOST=postgres'
    ports:
      - "8080:8080"
    networks:
      monitoring:
        aliases:
          - app
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'stat_buddy_service'
      POSTGRES_PASSWORD: 'stat_buddy_service'
      POSTGRES_SCHEMA: 'stat_buddy_service'
      POSTGRES_USER: 'stat_buddy_service'
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/pgdata
    networks:
      monitoring:
        aliases:
          - postgres

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
    networks:
      monitoring:
        aliases:
          - zipkin
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - 'GF_INSTALL_PLUGINS=grafana-clock-panel'
      - 'GF_SECURITY_ADMIN_USER=admin'
      - 'GF_SECURITY_ADMIN_PASSWORD=admin'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/var/lib/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus
volumes:
  grafana_data: { }
  pg_data: { }
  prometheus_data: { }

networks:
  monitoring: