version: '3.8'
services:
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'
    networks:
      monitoring:
        aliases:
          - zipkin
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - 'GF_INSTALL_PLUGINS=grafana-clock-panel'
      - 'GF_SECURITY_ADMIN_USER=admin'
      - 'GF_SECURITY_ADMIN_PASSWORD=admin'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/var/lib/prometheus
    networks:
      monitoring:
        aliases:
          - prometheus

  logstash:
    image: logstash:8.10.2
    ports:
      - '25826:25826'
      - '5046:5046'
    volumes:
      - ./config/elk/logstash/pipelines.yaml:/usr/share/logstash/config/pipelines.yml:ro
      - ./config/elk/logstash/pipelines:/usr/share/logstash/pipeline:ro
    networks:
      monitoring:
        aliases:
          - logstash
  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - node.name=elastic
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      monitoring:
        aliases:
          - elasticsearch
  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
      monitoring:
        aliases:
          - kibana

volumes:
  grafana_data: { }
  prometheus_data: { }
  elasticsearch_data: { }

networks:
  monitoring: