name: "Code quality workflow"

on:
  push:
    branches:
      - dev
      - master

permissions: read-all

concurrency:
  group: code_quality
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  code_quality:
    name: "Code quality"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: JavaSetup
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'

      - name: GradleSetup
        uses: gradle/gradle-build-action@v2.4.2

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: |
          ./gradlew test jacocoTestReport coverage

      - name: Scan
        run: |
          ./gradlew sonar -D"sonar.host.url"="https://sonarcloud.io" -D"sonar.login"=${{ secrets.SONAR_TOKEN }} -D"sonar.projectKey"=${{ secrets.SONAR_PROJECT_KEY }} -D"sonar.organization"=${{ secrets.SONAR_ORG }}